/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue';

export {};

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('@arco-design/web-vue')['Button']
    ADescriptions: typeof import('@arco-design/web-vue')['Descriptions']
    AntButton: typeof import('ant-design-vue/es')['Button']
    AntDescriptions: typeof import('ant-design-vue/es')['Descriptions']
    AntSpace: typeof import('ant-design-vue/es')['Space']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    DButton: typeof import('vue-devui/button/index.es.js')['Button']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElSpace: typeof import('element-plus/es')['ElSpace']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Header: typeof import('./../src/components/Header/index.vue')['default']
    IxButton: typeof import('@idux/components/button')['IxButton']
    IxSpace: typeof import('@idux/components/space')['IxSpace']
    NButton: typeof import('naive-ui')['NButton']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TSpace: typeof import('tdesign-vue-next')['Space']
  }
}

// For TSX support
declare global {
  const AButton: (typeof import('@arco-design/web-vue'))['Button'];
  const ADescriptions: (typeof import('@arco-design/web-vue'))['Descriptions'];
  const AntButton: (typeof import('ant-design-vue/es'))['Button'];
  const AntDescriptions: (typeof import('ant-design-vue/es'))['Descriptions'];
  const AntSpace: (typeof import('ant-design-vue/es'))['Space'];
  const ASpace: (typeof import('@arco-design/web-vue'))['Space'];
  const DButton: (typeof import('vue-devui/button/index.es.js'))['Button'];
  const ElButton: (typeof import('element-plus/es'))['ElButton'];
  const ElSpace: (typeof import('element-plus/es'))['ElSpace'];
  const ElTooltip: (typeof import('element-plus/es'))['ElTooltip'];
  const Header: (typeof import('./../src/components/Header/index.vue'))['default'];
  const IxButton: (typeof import('@idux/components/button'))['IxButton'];
  const IxSpace: (typeof import('@idux/components/space'))['IxSpace'];
  const NButton: (typeof import('naive-ui'))['NButton'];
  const NSpace: (typeof import('naive-ui'))['NSpace'];
  const RouterLink: (typeof import('vue-router'))['RouterLink'];
  const RouterView: (typeof import('vue-router'))['RouterView'];
  const SvgIcon: (typeof import('./../src/components/SvgIcon/index.vue'))['default'];
  const TButton: (typeof import('tdesign-vue-next'))['Button'];
  const TSpace: (typeof import('tdesign-vue-next'))['Space'];
}
