/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type { RouteRecordInfo, ParamValue, ParamValueOneOrMore, ParamValueZeroOrMore, ParamValueZeroOrOne } from 'vue-router';

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>, never>;
    '/component/': RouteRecordInfo<'/component/', '/component', Record<never, never>, Record<never, never>, never>;
    '/contain/': RouteRecordInfo<'/contain/', '/contain', Record<never, never>, Record<never, never>, never>;
    '/contain/components/layout': RouteRecordInfo<
      '/contain/components/layout',
      '/contain/components/layout',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/contain/components/main': RouteRecordInfo<
      '/contain/components/main',
      '/contain/components/main',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/contain/components/subAside': RouteRecordInfo<
      '/contain/components/subAside',
      '/contain/components/subAside',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/demo/': RouteRecordInfo<'/demo/', '/demo', Record<never, never>, Record<never, never>, never>;
    '/login/': RouteRecordInfo<'/login/', '/login', Record<never, never>, Record<never, never>, never>;
    '/login/components/banner': RouteRecordInfo<
      '/login/components/banner',
      '/login/components/banner',
      Record<never, never>,
      Record<never, never>,
      never
    >;
    '/login/components/login-form': RouteRecordInfo<
      '/login/components/login-form',
      '/login/components/login-form',
      Record<never, never>,
      Record<never, never>,
      never
    >;
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/views/index.vue': {
      routes: '/';
      views: never;
    };
    'src/views/component/index.vue': {
      routes: '/component/';
      views: never;
    };
    'src/views/contain/index.vue': {
      routes: '/contain/';
      views: never;
    };
    'src/views/contain/components/layout.vue': {
      routes: '/contain/components/layout';
      views: never;
    };
    'src/views/contain/components/main.vue': {
      routes: '/contain/components/main';
      views: never;
    };
    'src/views/contain/components/subAside.vue': {
      routes: '/contain/components/subAside';
      views: never;
    };
    'src/views/demo/index.vue': {
      routes: '/demo/';
      views: never;
    };
    'src/views/login/index.vue': {
      routes: '/login/';
      views: never;
    };
    'src/views/login/components/banner.vue': {
      routes: '/login/components/banner';
      views: never;
    };
    'src/views/login/components/login-form.vue': {
      routes: '/login/components/login-form';
      views: never;
    };
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info> ? Info['routes'] : keyof RouteNamedMap;
}
